Traceback (most recent call last):
  File "/home/jed/cu/numpde/VENV/lib/python3.10/site-packages/nbclient/client.py", line 767, in _async_poll_for_reply
    msg = await ensure_async(self.kc.shell_channel.get_msg(timeout=new_timeout))
  File "/home/jed/cu/numpde/VENV/lib/python3.10/site-packages/nbclient/util.py", line 99, in ensure_async
    result = await obj
  File "/home/jed/cu/numpde/VENV/lib/python3.10/site-packages/jupyter_client/channels.py", line 230, in get_msg
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jed/cu/numpde/VENV/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/jed/cu/numpde/VENV/lib/python3.10/site-packages/nbclient/client.py", line 1256, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/jed/cu/numpde/VENV/lib/python3.10/site-packages/nbclient/util.py", line 87, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/jed/cu/numpde/VENV/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/jed/cu/numpde/VENV/lib/python3.10/site-packages/nbclient/client.py", line 694, in async_execute
    await self.async_execute_cell(
  File "/home/jed/cu/numpde/VENV/lib/python3.10/site-packages/nbclient/client.py", line 993, in async_execute_cell
    exec_reply = await self.task_poll_for_reply
  File "/home/jed/cu/numpde/VENV/lib/python3.10/site-packages/nbclient/client.py", line 791, in _async_poll_for_reply
    error_on_timeout_execute_reply = await self._async_handle_timeout(timeout, cell)
  File "/home/jed/cu/numpde/VENV/lib/python3.10/site-packages/nbclient/client.py", line 843, in _async_handle_timeout
    raise CellTimeoutError.error_from_timeout_and_cell(
nbclient.exceptions.CellTimeoutError: A cell timed out while it was being executed, after 30 seconds.
The message was: Cell execution timed out.
Here is a preview of the cell contents:
-------------------
wind = 500 
fq(q, u, Du) = wind .* Du -one.(u), 1 * Du

fe = FESpace(5, 5, 10)
u0 = zero(fe.xn)
N = length(fe.xn)
sol = nlsolve(u -> fe_residual(u, fe, fq; bci=[1, N], bcv=[0, 0]), zero(fe.xn), method=:newton)
plot(fe.xn, sol.zero, marker=:auto, legend=:none)
-------------------

